### ISSUE TITLE
`kraft lib rm` removes some Kraftfile elements

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/kraftkit#1096]
### Describe the bug

before running `kraft lib rm musl`:
```
specification: '0.6'

template: https://github.com/unikraft/app-helloworld.git

name: helloworld
unikraft:
  version: staging
libraries:
  musl:
    version: staging
targets:
  - name: test
    plat: qemu
    arch: x86_64
  - qemu/arm64

```

after running `kraft lib rm musl`:
```
spec: '0.6'
name: helloworld
unikraft:
    version: staging
targets:
    - architecture: x86_64
      platform: qemu
    - architecture: arm64
      platform: qemu
```

As you can see the template was removed and also the target name.

This is most probably an internal problem that reflects also here.

### Expected behavior

The Kraftfile is left intact and only the specified library is removed
