### ISSUE TITLE
Passing volumes to kraft run via -v overwrites ``rootfs`` and ``volumes`` from ``Kraftfile``

### ISSUE THREAD

**Issue by LucaSeri** [unikraft/kraftkit#1340]
### Describe the bug

When working with an application that has some ``rootfs``/``volumes`` as part of the ``kraftfile``, attempting to pass additional volumes via the cli directly simply overrides the ``kraftfile`` as opposed to being added on top, resulting in very unintuitive behaviour.

### Steps to reproduce

```yaml
spec: v0.6

runtime: base-9p:latest

rootfs: ./Dockerfile

volumes:
  - ./data:/data

cmd: ["/server"]
```
When issuing ``kraft run``, the generated argument for ``qemu`` is as expected:
```bash
 vfs.fstab=[ "initrd0:/:extract:::" "fs2:/data:9pfs:::mkmp" ]
```

When issuing ``kraft run -v ./cli-vol:/cli-vol``, the generated argument for ``qemu`` only contains the cli passed volume:
```bash
vfs.fstab=[ "fs1:/cli-vol:9pfs:::mkmp" ]
```

### Expected behavior

For the volume to be added on top of the ``Kraftfile``
