### ISSUE TITLE
`kraft build` errors with "getting kernel image size: stat: no such file or directory" when both `name` and `target[].name` are set

### ISSUE THREAD

**Issue by antoineco** [unikraft/kraftkit#1490]
### Describe the bug

When attempting the build an app with the Kraftfile below, the following error is thrown at the end of the build:

```
 E  getting kernel image size: stat /git/myapp/.unikraft/build/kraftcloud-x86_64_kraftcloud-x86_64: no such file or directory
```

```yaml
specification: '0.6'

name: myapp

cmd: ["-x", "y"]

unikraft:
  source: https://github.com/unikraft/unikraft
  version: mybranch
  kconfig:
      CONFIG_LIBRAMFS: 'y'
      CONFIG_LIBSYSCALL_SHIM: 'y'
      CONFIG_LIBUKBLKDEV_DISPATCHERTHREADS: 'y'
      CONFIG_LIBUKCPIO: 'y'
      CONFIG_LIBUKNETDEV_EINFO_LIBPARAM: 'y'
      CONFIG_LIBVFSCORE: 'y'
      CONFIG_LIBVFSCORE_AUTOMOUNT_UP: 'y'
      CONFIG_OPTIMIZE_DEADELIM: 'y'
      CONFIG_OPTIMIZE_LTO: 'y'
      CONFIG_I8042: 'y'

targets:
  - name: kraftcloud-x86_64
    architecture: x86_64
    platform: kraftcloud

libraries:
  # ...
```

This is due to a conflict between `name: myapp` and `targets[0].name: kraftcloud-x86_64`
