### ISSUE TITLE
Error out on invalid platform

### ISSUE THREAD

**Issue by mkroening** [unikraft/kraftkit#185]
Given this `Kraftfile`:

```yaml
# Kraftfile
specification: v0.5

unikraft: stable

targets:
  - name: default
    architecture: x86_64
    platform: kvm
```

It would be great, if running `kraft build --plat linuxu` would return with a non-zero error code and provide an error message instead of silently not building anything.
