### ISSUE TITLE
Random library order breaks compilation

### ISSUE THREAD

**Issue by mkroening** [unikraft/kraftkit#186]
I am not sure if this is a problem with KraftKit or the Unikraft build system.

Given this `Kraftfile`:
```yaml
specification: v0.5

unikraft:
  version: stable
  kconfig:
    - CONFIG_LIBNOLIBC=y
    - CONFIG_LIBUKSCHED=y
    - CONFIG_LIBUKSCHEDCOOP=y

targets:
  - name: default
    architecture: x86_64
    platform: kvm

libraries:
  musl:
    version: stable
  lwip:
    version: stable
    kconfig:
      - CONFIG_LWIP_UKNETDEV=y
      - CONFIG_LWIP_TCP=y
      - CONFIG_LWIP_THREADS=y
      - CONFIG_LWIP_SOCKET=y
      - CONFIG_LWIP_AUTOIFACE=y
      - CONFIG_LWIP_IPV4=y
      - CONFIG_LWIP_DHCP=y
      - CONFIG_LWIP_SOCKET_PPOLL=n
```

Running `kraft build` in an otherwise empty directory sometimes succeeds and sometimes throws the following error:

```console
$ kraft build --build-log build-log.txt
[+] finding core/unikraft:stable...   [0.0s]
[+] finding lib/musl:stable...   [0.0s]
[+] finding lib/lwip:stable...   [0.0s]
[+] pulling core/unikraft:stable ### 100% [1.8s]
[+] pulling libs/musl:stable     ### 100% [2.4s]
[+] pulling libs/lwip:stable     ### 100% [3.0s]
[+] configuring default (kvm-x86_64) ### 100% [1.2s]
[+] preparing default (kvm-x86_64)   ### 100% [16.2s]
[-] error building default (kvm-x86_64): exit status 2   [31.0s]
    level=error msg="      |       ^~~~~~~~~"
    level=error msg="      |       locale_t"
    level=error msg="cc1: note: unrecognized command-line option '-Wno-array-parameter' may have been intended to silence earlier diagnostics"
    level=error msg="make[1]: *** [/root/pwd/kraftkit-foo/.unikraft/unikraft/support/build/Makefile.build:27: /root/pwd/kraftkit-foo/build/libposix_socket/driver.o] Error 1"
    level=error msg="make: *** [Makefile:1023: sub-make] Error 2"
exit status 2
```

The [build-log.txt](https://github.com/unikraft/kraftkit/files/10426061/build-log.txt) does not contain any useful information or reference to this issue at all, as far as I can tell.

It feels like this problem happens more often when running as subprocess of the unikraft-rs build script. The Kraftfile might also be reducible. This problem might have something to do with CPU load or parallel make jobs (I am running in a Docker container on a 24 core CPU).

Is there some way to make KraftKit print all the log messages instead of only the recent ones and swallowing the rest?
