### ISSUE TITLE
Can't run with multiple targets

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/kraftkit#198]
### Describe the bug

If no name is specified for targets, targets default to the package name. This means that they will all have the same name, instead of specifying more details.

In the screenshot below you can see `x86_64-kvm` and  `x86_64-linuxu`.
![image](https://user-images.githubusercontent.com/46280801/214546691-beac857f-e9cd-45cf-b47c-be46c9a2ad50.png)

More than this, because they all have the same name, they essentially become the same option (the first one).
This means that other options apart from the first one can't be selected.

### Steps to reproduce

Use this kraft configuration inside helloworld:

```
---
specification: '0.5'
name: helloworld
unikraft:
  version: stable
targets:
  - architecture: x86_64
    platform: kvm
  - architecture: x86_64
    platform: linuxu
```

1. Build the application using the default command.
2. Run the application `sudo ~/kraftkit/dist/kraft run -m x86_64 -H qemu ./build/helloworld_kvm-x86_64`

### Expected behavior

After selecting the desired target, it boots correctly and you see the helloworld prompt.

```
iPXE (https://ipxe.org) 00:02.0 C100 PCI2.10 PnP PMM+03F8B2C0+03ECB2C0 C100



Booting from ROM...
Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
                           Janus 0.11.0
Hello world!

```

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian

**Comment by craciunoiuc** [comment]
This is fixed, targets now also have the plat/arch specified:

```
 D  using runner=kraftfile-unikraft
[?] select target:
    custom_name (qemu/x86_64)
  ▸ helloworld (qemu/x86_64)
```

```yaml

targets:
  - arch: x86_64
    plat: fc
  - name: custom_name
    arch: x86_64
    plat: qemu
  - arch: x86_64
    plat: qemu
```
