### ISSUE TITLE
`kraft run` does not infer `plat`/`arch` from command

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/kraftkit#199]
### Describe the bug

Kraft should limit the shown targets to the ones that match given architecture and platform in the command.
This would make choosing a single target a lot easier when dealing with a lot of targets.

### Steps to reproduce

Use a kraft config with multiple targets for helloworld:

```
---
specification: '0.5'
name: helloworld
unikraft:
  version: stable
targets:
  - architecture: x86_64
    platform: kvm
  - architecture: x86_64
    platform: linuxu
```

Specify the architecture and platform for kraft run: `sudo ~/kraftkit/dist/kraft run -m x86_64 -p kvm -H qemu ./build/helloworld_kvm-x86_64`

### Expected behavior

It should auto-run the last remaining option and show the helloworld output.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian
