### ISSUE TITLE
Add recommended packages to nFPM and webinstall

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#623]
### Feature request summary

This issue tracks adding additional necessary packages to the nFPM "overrides" "recommends" packages to the goreleaser stable configuration.

The following additional packages should be recommended during the installation of KraftKit (this is a Debian-example):
```
apt-get install -y --no-install-recommends build-essential libncurses-dev flex git wget socat bison unzip qemu-system;
```

The implementation should use the `overrides` per-suported nFPM.
```yaml
    # All fields above marked as `overridable` can be overridden for a given
    # package format in this section.
    overrides:
      # The dependencies override can for example be used to provide version
      # constraints for dependencies where  different package formats use
      # different versions or for dependencies that are named differently.
      deb:
        dependencies:
          - baz (>= 1.2.3-0)
          - some-lib-dev
        # ...
      rpm:
        dependencies:
          - baz >= 1.2.3-0
          - some-lib-devel
        # ...
      apk:
        # ...
```
See: https://goreleaser.com/customization/nfpm/

Finally, an additional prompt should be added to the web install script to query whether the user would like to have the recommended packages to be installed.

### Related architectures

None

### Related platforms

None
