### ISSUE TITLE
kraft build fails to correctly filter targets with "kvm" platform

### ISSUE THREAD

**Issue by jake-ciolek** [unikraft/kraftkit#657]
### Describe the bug

Filtering using the -p flag and targetting "kvm" specifically, doesn't match targets from the kraft.yaml file.

Before filtering, "kvm" gets aliased to "qemu". As a result, the filtering matches no targets.

### Steps to reproduce

Given this sample kraft.yaml file:

```yaml
specification: '0.5'
name: helloworld
unikraft:
  version: stable
targets:
  - architecture: x86_64
    platform: kvm
  - architecture: arm64
    platform: xen
```

Run the command:

```sh
kraft build -p kvm
```

Build exits with the error:

```sh
no choices provided.
 ```

### Expected behavior

Command should select the target with platform "kvm".

### Relevant log output

```shell
no choices provided.
```
