### ISSUE TITLE
kraft build appends desired target twice in selection screen

### ISSUE THREAD

**Issue by jake-ciolek** [unikraft/kraftkit#658]
### Describe the bug

When executing the command kraft build -p xen -m arm64 -t target1 on a kraft.yaml file containing a unique target described by the platform, architecture, and name combination, the expected behavior is for the command to match and select only the target "target1 (xen/arm64)".

However, the current behavior is that the desired target (xen/arm64) gets appended twice during the filtering process, and it does not get selected exclusively. This is inconsistent with the expected behavior, as the platform, architecture, and name combination describes the target uniquely.

### Steps to reproduce

Given this sample kraft.yaml file:

```yaml
specification: '0.5'
name: helloworld
unikraft:
  version: stable
targets:
  - architecture: x86_64
    platform: kvm
    name: target1
  - architecture: arm64
    platform: xen
    name: target1
```

Run the command: 

```sh
kraft build -p xen -m arm64 -t target1
```

The user is taken to the selection screen and sees:

```sh
▸ target1 (qemu/x86_64)
target1 (xen/arm64)
target1 (xen/arm64)
```

### Expected behavior

The command should match only the target "target1 (xen/arm64)". The user should not see the selection screen.
