### ISSUE TITLE
Publish homebrew tap via GoReleaser

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#674]
### Feature request summary

This issue tracks adding brew to the list of distributables from GoReleaser for KraftKit.

A new tap repository has been created at https://github.com/unikraft/homebrew-cli

Which will ultimately allow for KraftKit to be installed via:
```
brew install unikraft/cli/kraftkit
```

A new entry in GoReleaser's config needs to be added to the stable channel:

```yaml
brews:
  - description: "Build and use highly customized and ultra-lightweight unikernels."
    name: kraftkit
    install: |
      bin.install "kraft"
    homepage: "https://kraftkit.sh"
    license: "BSD-3-Clause"
    skip_upload: auto
    tap:
      owner: unikraft
      name: homebrew-cli
      token: "{{ .Env.GITHUB_TOKEN }}"
```

More details can be found here: https://goreleaser.com/customization/homebrew/?h=tap

Additionally, though not in the code snippet above,`bison` and `gsed` for macOS are required. These need to be injected into the [new configurable toolchain](https://github.com/unikraft/kraftkit/issues/673) since they are installed at alternative (homebrew-specific) PATHs.

The following additional brew dependencies need to be part of the install:

```
brew install gnu-sed
brew install make
brew install m4
brew install gawk
brew install grep
brew install wget
brew install qemu
brew install socat
# ...for compiling x86_64 Unikernels
brew install x86_64-elf-binutils
brew install x86_64-elf-gcc
# ...for compiling aarch-64 Unikernels
brew install aarch64-elf-binutils
brew install aarch64-elf-gcc
```

### Related architectures

None

### Related platforms

None

### Additional context

Not sure if the environmental variable `GITHUB_TOKEN` will work.

GitHub-Depends-On: #675
