### ISSUE TITLE
Add cosign to stable release

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#675]
### Feature request summary

This issue tracks adding cosign to the release such that artifacts are validated on platforms such as macOS.

The addition simply requires adding cosign to the GoReleaser configuration for the stable channel and introducing the public key `cosign.pub` and respective password as a repository secret.

```yaml
signs:
  - id: cosign
    cmd: cosign
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: checksum
```

### Related architectures

None

### Related platforms

None
