### ISSUE TITLE
Disabling TLS verification in config's auth takes no effect when pushing

### ISSUE THREAD

**Issue by jake-ciolek** [unikraft/kraftkit#924]
### Describe the bug

Using kind, I've deployed a local harbor registry and pointed to it via my /etc/hosts file:

```
172.18.0.2 kindharbordeployment.com
```

I logged to it via kraft login and my config looks as follows:

```yaml
auth:
    kindharbordeployment.com:
        user: admin
        token: Harbor12345
        endpoint: kindharbordeployment.com
        verify_ssl: false
```

I've built a target, packaged it and tried to push it to my registry with:

```sh
kraft pkg push --as oci kindharbordeployment.com/jakub/mkernel:latest
```

Unfortunately, the push fails with certificate verification error:

```console
<!> pushing kindharbordeployment.com/jakub/mkernel:latest                                                                                                                    0% [0.0s]
 E  Get "https://kindharbordeployment.com/v2/": tls: failed to verify certificate: x509: certificate is valid for ingress.local, not kindharbordeployment.com
 ```

### Expected behavior

The certificate verification issues should be ignored if verify_ssl is set to false.
